### ISSUE TITLE
Tech#, Emp# fields mat have to be strings

### ISSUE THREAD

**Issue by scaspers** [scaspers/D3-API#12]
There are valid employee numbers in our system for the xlube that begin with '00'  (0010, 0020, 0030, ...) and these are not valid in json.
Fix is to either trim the leading zeros or make the value a sting.

**Comment by DanielCaspers** [comment]
Lets make them strings

**Comment by scaspers** [comment]
This is done, awaiting the go ahead to move the v2 API onto v1
