### ISSUE TITLE
Provide file locking mechanism which DI can pass from client to D3-API

### ISSUE THREAD

**Issue by DanielCaspers** [scaspers/D3-API#13]
As we discussed previously, DI should be able to mediate/proxy a client's requests to the file locking scheme in D3-API without D3-API thinking that DI is the same user each time.

You can choose the method. Using a user's auth token/ payload object sounded fine to me. 

Required by https://github.com/DanielCaspers/DigitalInspection/issues/50

No rush from me; Just can't resolve locking completely until this is ready.

**Comment by DanielCaspers** [comment]
Is the auth data passed back and for the login going to be a Employee ID (4 digit number) and password? I was wondering as I'm writing the login view and can provide some nifty validation with minimal effort if I know the username type for the auth system.

**Comment by scaspers** [comment]
What do you think about a 7 digit number (company#+employee#) ie 0044067

**Comment by DanielCaspers** [comment]
I think that makes sense. If you want in the future, we could also create 1 button or checkbox per store so people would only type in the 4 digits, but I have to imagine typing 7 digits will be faster. 

I'll just make sure that the username only accepts 7 digit entries

**Comment by scaspers** [comment]
The auth endpoint is completed and ready for use on v2 of the API.  The AppKey ending with "z" will now require authentication using the auth endpoint.
2 test users have been setup and I'll email you the usernames and passwords.
See the [help ](https://d3-devel.murphyauto.net/api/v2/help)for other details.
