### ISSUE TITLE
api/orders (and similar endpoints returning object arrays) should *directly* return array

### ISSUE THREAD

**Issue by DanielCaspers** [scaspers/D3-API#3]
*Problem*
Unnecessary nesting of returned array of objects makes for a less usable API that requires needless unpackaging of data for consumers.

`{
order: [
    {obj}, {obj}
]
}`

Should simply be

`
[
 {obj},
 {obj}
]
`

if at all possible.

*Side effects*
Extra DTOs (Data Transfer Objects) need to be defined and maintained to unpack data. These don't represent client information and serve as nothing but glorified buckets which ALL Http data must be cast into on every request.

**Comment by scaspers** [comment]
The API endpoints 'orders' and 'clients' have been modified to return an array of objects.
