### ISSUE TITLE
Discuss Data Model Types and Consuming API Sanitation Expecations

### ISSUE THREAD

**Issue by DanielCaspers** [scaspers/D3-API#4]
*Motivation*
In using the D3 API, I found a lot of things that were treated as strings that I wasn't expecting to be. I'm trying to figure out where the changes to the underlying data model would be best made.

1) My Mapping Layer from PIC to DI
1.1) Better/more graceful parsing logic of incomplete string data
2) DI Models should just go with the flow and use current PIC PHP model representation
3) PIC models in PHP could be made more advanced, and use some of the types mentioned below

*Action Items before we talk*
Read the models I currently have and notice the data types
- [Customer](https://github.com/DanielCaspers/DigitalInspection/blob/master/DigitalInspection/Models/Customer.cs)
- [Vehicle](https://github.com/DanielCaspers/DigitalInspection/blob/master/DigitalInspection/Models/Vehicle.cs)
- [Work Order](https://github.com/DanielCaspers/DigitalInspection/blob/master/DigitalInspection/Models/WorkOrder.cs)

Determine if you care about data types for
- Vehicle Year
- Vehicle Engine
- Vehicle Transmission
- Vehicle Odometer
- Order Dates, and all Dates

**Comment by scaspers** [comment]
JSON can transfer integers but NOT with leading zeros as in orderID, clientID.

ORDERSTATUS: Changed to integer.
YEAR: Made Year an integer.
ENGINE SIZE: Should be string as sometimes alpha chars are used to denote special attributes (turbo, DOHC, etc).
TRANS: Should be string for special info reasons (6spd etc).
ODOMETER: Changed to integer.
DATES:  JSON does not transfer dates except as strings.  We should agree on format and do needed conversions on each end.
PHONE: In PICK the number is stored as an integer (7 or 10 digits, typically 10).  I changed to an integer for now.

**Comment by DanielCaspers** [comment]
I agree on leading 0 IDs. 

Here are the changes I'll make on my end. 

EngineDisplacement will become Engine, of type string. 

Transmission may require changes to our wireframes. We previously planned on just "Auto" and "Manual" radio buttons. Perhaps we should discuss further to figure out how to make data entry fastest for this going forward. 

Dates: I'm considering MS from 1970 epoch as a number (type 'long') . If you have that, we'll get much improved resolution over current version, since rendering Date Times is then useless because they would all be midnight. We can talk more though. 

For many reasons, lets switch Phone back to string. 

If a parameter is optional,  I think nullable would be best. However, based on some of the work orders I saw through the API, maybe we should discuss which are optional in the first place?

**Comment by DanielCaspers** [comment]
More thoughts from SO community on Dates. https://stackoverflow.com/a/15952652/2831961

I still think it's probably a bit easier for us to do MS, bit following that ISO sounds smart too.

**Comment by scaspers** [comment]
Dates: Most, if not all, of the current dates are in a date only format (no time) so converting them to MS or ISO will still generate midnight.  The new status' can have a MS timestamp if we feel this is helpful.  Still using one of the recognized formats would be a good idea.  I can easily do either.

Phone is back to string.

**Comment by scaspers** [comment]
Dates are now in unix timestamp epoch as integers (seconds not milliseconds)

**Comment by DanielCaspers** [comment]
One small note to consider with Epoch.  

_If we ever actually use Times in the DateTime, you'd be best served serializing the times with respect to UTC 0 (GMT) instead of in UTC -6._

 Doesn't matter for now since I'll filter out the time, but something to be aware of. I won't be doing any special treatment of it for now just because we don't have specific times yet.

**Comment by DanielCaspers** [comment]
Or did you adjust? I'm just confused because when attempting to deserialize the new dates, they all say 6 AM. Are you doing custom math on top of serialization?

**Comment by scaspers** [comment]
The timestamps were originally in the servers tz.  Is now changed to UTC.

**Comment by DanielCaspers** [comment]
I don't know if you live pushed to the API, but all of my timestamps are still 6am. NBD for now though

**Comment by scaspers** [comment]
Whoops.  Try it again please.

**Comment by DanielCaspers** [comment]
;) Bueno!

**Comment by DanielCaspers** [comment]
On an unrelated note, go ahead and play with stable.

**Comment by scaspers** [comment]
I changed the date again.  If my server is creating a local time of 04/06/17 12:00:00am (midnight) then UTC would be 04/06/17 05:00:00am (don't forget daylight savings).  
If the local time is 01/01/17 12:00:00am then UTC would be 01/01/27 06:00:00am because daylight savings was not in effect then.  Right????

**Comment by DanielCaspers** [comment]
Totally spaced DST....

I don't think it works quite like that. I think we veer to 5hrs off GMT at some times. See wikipedia https://en.wikipedia.org/wiki/UTC_offset#Daylight_saving_time

 Started skimming this though, this looks like a good resource. https://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices

**Comment by DanielCaspers** [comment]
I'm just trying to make sure I'm on the same page before we close this task out since I think everything is done in this task.

Are we using Local or UTC Time now? I'm not trying to rock the boat; I just don't remember :)

Please review my newly added code for time handling to make sure I'm not being stupid.

https://github.com/DanielCaspers/DigitalInspection/blob/master/DigitalInspection/Utils/DateTimeUtils.cs

**Comment by scaspers** [comment]
The unix time stamps will be UTC (that is the unix standard).  Everything is displayed as local time which is either -6 CST or -5 CDT.  If you can grab the current time offset from the server that might be best as we wouldn't have to manually change the offset at DST.

**Comment by scaspers** [comment]
... or if your code can access the built-in unix time processing it might save you some time.

**Comment by DanielCaspers** [comment]
I think the C# code I've shown handles those cases. I'll just make sure to always send back in flat UTC and then when it comes in transform it to display in local time. So I'll have to probably remove that custom code I have in ToUnixTimeSeconds()
