### ISSUE TITLE
Need for expanded Vehicle data\information

### ISSUE THREAD

**Issue by scaspers** [scaspers/D3-API#6]
We will want expanded user editable vehicle information available from API and green screen.

**Comment by DanielCaspers** [comment]
What is the current status of this? Any ETA by chance? I'm asking because the remainder of https://github.com/DanielCaspers/DigitalInspection/issues/38 depends on it.

**Comment by scaspers** [comment]
I should have this done end of day 7/15 along with WO history, current RS list, and Customer comments.

**Comment by DanielCaspers** [comment]
Cool! I probably won't be working on it again until next Monday or Wednesday. No pressure :-)

**Comment by scaspers** [comment]
This is complete for now.  Likely will be adding at least one more piece of data in the not too distant future that will be some estimate summary and/or details. Will make new issue for that.
