### ISSUE TITLE
Make WorkDesc always as string[] type?

### ISSUE THREAD

**Issue by DanielCaspers** [scaspers/D3-API#7]
Would it be fairly easy to make WorkDesc always a string[] type? Just wondering if the way you returned it was a nicety for me, or not. 

I can look into how to how to make a union type (String or String array) in C# if this isn't a 15 minute or shorter change, but for future clients using this in strongly typed languages, its nice to know its always the same type. 

String[] type
![image](https://cloud.githubusercontent.com/assets/6056563/26765585/88519510-4944-11e7-9d01-e2824b8b8b49.png)

String type
![image](https://cloud.githubusercontent.com/assets/6056563/26765598/a0cc8910-4944-11e7-8517-c04a0f9860f6.png)

**Comment by DanielCaspers** [comment]
String type
![image](https://cloud.githubusercontent.com/assets/6056563/26765585/88519510-4944-11e7-9d01-e2824b8b8b49.png)

String[] type
![image](https://cloud.githubusercontent.com/assets/6056563/26765598/a0cc8910-4944-11e7-8517-c04a0f9860f6.png)

**Comment by scaspers** [comment]
This was just the easiest way as it is stored this way in PICK.  Currently each line is stored separately, not as a paragraph.  With some conversion on my end I can convert to one string with cr/lf added between.  Would this be a help?

**Comment by DanielCaspers** [comment]
Hey, just found out this is blocking me now.

Can you enforce this at the PICK or PHP layer? It would be difficult for me to proceed past this in a typesafe language, because discriminated unions (either string OR string array) are a major pain to implement, serialize and deserialize, especially since I didn't write my serialization layer. However, since you have written yours, I think this may be the best place to put some simple typechecking in that would wrap a single string in an array if that is what the field contains?

**Comment by scaspers** [comment]
Are you asking for a single string?  With cr/lf for line breaks or another delimiter maybe?  I could send it as a single string with ACSII 253 as a line delimiter as this is it's native form.

**Comment by DanielCaspers** [comment]
We can do either a single string all of the time, or always make it a nullable array where when defined, it contains 0 or more strings. Either approach should be ok. I'm partial to the latter, but either would work.

**Comment by DanielCaspers** [comment]
Right now, I can get requests working back and forth on sets that use the property one way or the other, but the table view will break until this is resolved because I can't make a domain object with the same name for two different types, and I can't assign union types or anonymous types on a model in C#.

**Comment by scaspers** [comment]
workDesc is now always string[]
