### ISSUE TITLE
order endpoint - orderStatus,  data representation

### ISSUE THREAD

**Issue by scaspers** [scaspers/D3-API#9]
The new status system is ready to implement in PICK using [this](https://docs.google.com/spreadsheets/d/1GhVTRwj8GXdf7GOHxaAH8Ts4M_T_0eLdc8rXRYdik3E/edit#gid=0).
The data is currently returned as an integer.  The new system has the status, a timestamp and can have an Emp# or port# that made the change.

Do we want the status returned as an integer, as a string description or an object?
Do we want status only (numeric, string or object?) or do we want the timestamp included?

**Comment by DanielCaspers** [comment]
New expected status format as an object
`{
    statusCode: number.
    statusDesc: string,
    statusTimestamp: long,
    statusMisc: string
}`

**Comment by scaspers** [comment]
All set

**Comment by DanielCaspers** [comment]
Updated on my side. Made a push to stable and weekly so you can continue to use them without all the serializer errors.
